#!/bin/bash

# The first argument is the file list
files=("GEMINI.md" "README.md" "artisan" "blueprint.md" "composer.json" "composer.lock" "package-lock.json" "package.json" "phpunit.xml" "spread_commits.sh" "vite.config.js" "bootstrap/app.php" "bootstrap/providers.php" "config/app.php" "config/auth.php" "config/cache.php" "config/database.php" "config/filesystems.php" "config/logging.php" "config/mail.php" "config/queue.php" "config/sanctum.php" "config/services.php" "config/session.php" "public/favicon.ico" "public/index.php" "public/robots.txt" "routes/console.php" "routes/web.php" "tests/TestCase.php" "app/Models/Category.php" "app/Models/Notification.php" "app/Models/Order.php" "app/Models/OrderItem.php" "app/Models/Payment.php" "app/Models/Product.php" "app/Models/Review.php" "app/Models/User.php" "app/Models/Vendor.php" "app/Providers/AppServiceProvider.php" "database/factories/CategoryFactory.php" "database/factories/OrderFactory.php" "database/factories/OrderItemFactory.php" "database/factories/PaymentFactory.php" "database/factories/ProductFactory.php" "database/factories/ReviewFactory.php" "database/factories/UserFactory.php" "database/factories/VendorFactory.php" "database/migrations/0001_01_01_000000_create_users_table.php" "database/migrations/0001_01_01_000001_create_cache_table.php" "database/migrations/0001_01_01_000002_create_jobs_table.php" "database/migrations/2025_11_19_232858_create_personal_access_tokens_table.php" "database/migrations/2025_11_19_232919_create_vendors_table.php" "database/migrations/2025_11_19_232929_create_products_table.php" "database/migrations/2025_11_19_232959_create_categories_table.php" "database/migrations/2025_11_20_000126_create_notifications_table.php" "database/migrations/2025_11_20_001128_create_orders_table.php" "database/migrations/2025_11_20_001144_create_order_items_table.php" "database/migrations/2025_11_20_001159_create_payments_table.php" "database/migrations/2025_11_20_001216_create_reviews_table.php" "database/seeders/CategorySeeder.php" "database/seeders/DatabaseSeeder.php" "database/seeders/OrderItemSeeder.php" "database/seeders/OrderSeeder.php" "database/seeders/PaymentSeeder.php" "database/seeders/ProductSeeder.php" "database/seeders/ReviewSeeder.php" "database/seeders/UserSeeder.php" "database/seeders/VendorSeeder.php" "resources/css/app.css" "resources/js/app.js" "resources/js/bootstrap.js" "resources/views/welcome.blade.php" "tests/Feature/ExampleTest.php" "tests/Unit/ExampleTest.php" "app/Http/Controllers/Controller.php" "app/Http/Controllers/ProductController.php" "resources/views/product/show.blade.php")

for file in "${files[@]}"
do
    git add "$file"
    git commit -m "feat: add $file"
done
